#!/bin/bash

if [ $# -eq 0 ]; then
    echo "No arguments provided. Please specify the name of the graph."
    exit 1
fi
g++ Main.C 
if [ $? -ne 0 ]; then
    echo "Error"
    exit 1
fi
echo "$1" | ./a.out | less

if [ $? -ne 0 ]; then
    echo "Error"
    exit 1
fi
rm a.out 
